
- name: Creating two file for the script that is needed to be executed to genrate certificates
  file:
    path: ~/{{ item }}
    state: touch 
  with_items:
    - "{{ SecurityScriptName }}"
    - instances.yml

- name: Copying the file from template to genearte certificates
  copy:
    src: "{{ item.Source }}"
    dest: "{{ item.destination }}"
    force: yes
  loop: "{{ AddingTemplatedForCertificates }}"

- name: Generating certificates by executing script
  shell: bash {{ SecurityScriptName }}
  args:
    chdir: ~/