---
- name: Copying the file from template to genearte certificates
  copy:
    src: "{{ item }}"
    dest: "{{ CertificateScriptPath }}"
    force: true
  with_items:
    - wazuh-cert-tool.sh
    - instances.yml

- name: Generating certificates by executing script
  command: "bash {{ CertificateScriptPath }}wazuh-cert-tool.sh"
  changed_when: true
