
- name: Install the Filebeat package
  apt:
    name: filebeat
    state: present

- name: configuring filebeat
  template:
    src: "{{ item.Source }}"
    dest: "{{ item.destination }}"
    mode: '0744'
  loop: "{{ ConfigureFilebeat }}"

- name: Unarchive a filebeat modules
  unarchive:
    src: "{{ FileBeatSourceUrl }}"
    dest: "{{ FilebeatModulePath }}"
    remote_src: yes

- name: Creating directory
  file:
    path: "{{ FilebeatConfigPath }}/certs"
    state: directory

- name: Copying the certificates
  copy:
    src: "{{ item }}"
    dest: "{{ FilebeatConfigPath }}/certs/"
    remote_src: yes
  with_items:
    - "{{ CertificatePath }}/filebeat-key.pem"
    - "{{ CertificatePath }}/filebeat.pem"
    - "{{ CertificatePath }}/root-ca.pem"

- name: FilebeatServiceStartEnableAndReload
  systemd:
    name: filebeat
    daemon_reload: yes
    enabled: yes
    state: started  

- name: Testing the configueration
  command: filebeat test output
  register: output2

- name: Printing tested output
  debug:
    msg: "{{ output2.stdout }}"