---
- name: Install the Filebeat package
  apt:
    name: filebeat
    state: present

- name: configuring filebeat
  template:
    src: "{{ item.Source }}"
    dest: "{{ item.destination }}"
    mode: '0744'
  loop: "{{ ConfigureFilebeat }}"

- name: Unarchive a filebeat modules
  unarchive:
    src: "{{ FileBeatSourceUrl }}"
    dest: "{{ FilebeatModulePath }}"
    remote_src: true

- name: Creating directory
  file:
    path: "{{ FilebeatConfigPath }}/certs"
    state: directory

- name: Copying the certificates
  copy:
    src: "{{ item }}"
    dest: "{{ FilebeatConfigPath }}/certs/"
    remote_src: true
  with_items:
    - "{{ CertificatePath }}/filebeat-key.pem"
    - "{{ CertificatePath }}/filebeat.pem"
    - "{{ CertificatePath }}/root-ca.pem"
  notify: FilebeatServiceStartEnableAndReload

- name: Running all handlers
  meta: flush_handlers

- name: Testing the configueration
  command: filebeat test output
  register: output2
  changed_when: true

- name: Printing tested output
  debug:
    msg: "{{ output2.stdout }}"
