---
- name: Install the Kibana package
  apt:
    name: opendistroforelasticsearch-kibana
    state: present

- name: Configuring kibana
  template:
    src: kibana.yml.j2
    dest: "{{ KibanaConfigPath }}/kibana.yml"

- name: creating directory
  file:
    path: "{{ KibanaBinaryPath }}/data"
    state: directory
    owner: "{{ KibanaUser }}"
    group: "{{ KibanaUser }}"
    recurse: true

- name: Change the working directory to somedir/ before executing the command
  command: "sudo -u kibana {{ KibanaPluginPath }} install {{ KibanaURLPlugin }}{{ WazuhVersion }}_{{ ESVersion }}-1.zip"
  changed_when: true

- name: Creating directory for certificates
  file:
    path: "{{ KibanaConfigPath }}/certs"
    state: directory
    recurse: true

- name: Copying the required certificates to kibana
  copy:
    src: "{{ item }}"
    dest: "{{ KibanaConfigPath }}/certs/"
    owner: "{{ KibanaUser }}"
    group: "{{ KibanaUser }}"
    remote_src: true
  with_items:
    - "{{ CertificatePath }}/kibana-key.pem"
    - "{{ CertificatePath }}/kibana.pem"
    - "{{ CertificatePath }}/root-ca.pem"

- name: Specified filename to the capabilities specified
  community.general.capabilities:
    path: "{{ KibanaBinaryPath }}/node/bin/node"
    capability: cap_net_bind_service=+ep
    state: present
  notify:
    - KibanaServiceStartEnableAndReload

- name: Running all handlers
  meta: flush_handlers
