---
- name: Installing prerequist package
  apt:
    update_cache: "yes"
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - gnupg
    - apt-transport-https
    - libcap2-bin
    - software-properties-common
    - lsb-release
