- name: Install the GPG key for wazuh
  apt_key:
    url: "{{ WazuhKeyUrl }}"
    state: present

- name: Adding wazuh repository
  apt_repository:
    repo: "{{ WazuhRepoUrl }}"
    state: present

- name: Updating apt cache for repo
  apt:
    update_cache: yes

- name: Installing wazuh-manager 
  apt:
    name: wazuh-manager={{ WazuhVersion }}-1
    state: present

- name: Configuration wazuh
  template:
    src: ossec.conf.j2
    dest: "{{ WazuhConfigPath }}"
  
- name: WazuhServiceStartEnableAndReload
  systemd:
    name: wazuh-manager
    daemon_reload: yes
    enabled: yes
    state: started

